inherits = "base16_default" 

"ui.background" = {}

"ui.linenr" = {}
"ui.linenr.selected" = { fg="black", bg="gray", modifiers = ["bold"] }
 
"ui.selection" = { fg="black", bg="cyan", modifiers = [ "bold" ] }
"ui.selection.primary" = { fg="black", bg="magenta", modifiers = [ "bold" ] }
 
"ui.gutter" = { fg = "gray" }

"ui.virtual.ruler" = { bg = "gray" }

[palette]
white = "#cfcfcf"
black = "#303030"
