[[language]]
name = "python"
language-servers = [ "pyright" ]


[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

[language-server.typescript-language-server]
config = { format = {}, maxTsServerMemory = 20480 }

[[languages]]
name = "clojure"
indent = { tab-width = 2, unit = " " }
