[[language]]
name = "python"
language-servers = [ "pyright" ]


[[language]]
name = "rust"
language-servers = [ "rust-analyzer" ]

[language-server.typescript-language-server]
config = { format = {}, maxTsServerMemory = 20480 }

# [[language]]
# name = "typescript"
# language-servers = [ "vtsls", "eslint" ]

# [language-server.vtsls]
# args = ["--stdio"]
# command = "vtsls"

# [language-server.eslint]
# args = ["--stdio"]
# command = "vscode-eslint-language-server"

# [language-server.eslint.config]
# format = true
# nodePath = ""
# onIgnoredFiles = "off"
# packageManager = "yarn"
# quiet = false
# rulesCustomizations = []
# run = "onType"
# useESLintClass = false
# validate = "on"
# codeAction = { disableRuleComment = { enable = true, location = "separateLine" }, showDocumentation = { enable = true } }
# codeActionOnSave = { mode = "all" }
# experimental = { }
# problems = { shortenToSingleLine = false }
# workingDirectory = { mode = "auto" }
