#!/usr/bin/env bash
directory=$1
main_command=${2:-nvim}
layout=${3:-main-vertical}
pane_count=${4:-2}

if [ ! -d "$1" ]; then
    >&2 echo "Target directory is missing/invalid."
    exit 1
fi

[ -n "$pane_count" ] && [ "$pane_count" -eq "$pane_count" ]
if [ $? -ne 0 ]; then
    >&2 echo "Pane count must be a number, not: $pane_count"
    exit 1
fi

if [ -f $directory/Pipfile ]; then
    env_cmd="pipenv run"
    shell_cmd="pipenv shell"
fi

tmux new-window -c $1 "$env_cmd $main_command"
for run in $(seq 1 $pane_count)
do
    tmux split-window -c $1 -v $shell_cmd
done

tmux select-layout $layout
